config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :blogs do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = current_user.blogs.build(blog_params)
      render 'new'
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render 'new'
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました"
      else
        render 'new'
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    @blog.image.cache! unless @blog.image.blank? # 既に画像が存在する場合にキャッシュを作成する
  end

  def update
    if params[:back]
      render :edit
    else
      if @blog.update(blog_params)
        redirect_to blogs_path, notice: "ブログを編集しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    @blog.id = params[:id]
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:id, :title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id]) 
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) # ストロングパラメータ設定
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end

    def show
      @user = User.find(params[:id])
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    # userキーのpermit以下のパラメータのみ受け取るという意味
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      confirm_blog_path
    end
  end

  def confirm_new_or_edit
    unless @blog.id?
      blogs_path # blogs_pathはメソッドでindexかcreateに移動先が別れる。メソッドの指定はconfirm_form_methodで指定する。
    else
      blog_path
    end
  end

  def confirm_form_method
    @blog.id ? 'patch' : 'post' # @blog.idが存在する(=true)のとき、httpメソッドがpatch, 存在しないときはpost
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.slim
= form_with(model: @blog, local: true, url: choose_new_or_edit) do |f|
  - if @blog.errors.any?
    div#error_explanation
      h2 #{@blog.errors.count}件のエラーがあります。
      ul
      - @blog.errors.full_messages.each do |msg|
        li #{msg}

  div.blog_title.form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  div.blog_content.form-group
    = f.label :content
    = f.text_field :content, class: 'form-control'
  div.blog_image.form-group
    = f.label :image
    = image_tag(@blog.image.url) if @blog.image && @blog.image.url
    = f.file_field :image, class: 'form-control-file'
    = f.hidden_field :image_cache
  = f.submit
= link_to 'ブログ一覧画面に戻る', blogs_path

app/views/blogs/confirm.html.slim
h3 以下の内容で、送信する

= form_with(model: @blog, url: confirm_new_or_edit, method: confirm_form_method, local: true) do |f|
  = f.hidden_field :title
  = f.hidden_field :content
  = f.hidden_field :image
  = f.hidden_field :image_cache

  p タイトル: #{@blog.title}
  p 本文: #{@blog.content}
  p 画像: #{image_tag(@blog.image.url) if @blog.image && @blog.image.url}
  - if @blog.id # 更新時と新規投稿時でボタンの内容を変える
    = f.submit '更新する'
  - else
    = f.submit '登録する'

= form_with(model: @blog, url:new_blog_path, local: true, method: "get") do |f|
  = f.hidden_field :title
  = f.hidden_field :content
  = f.hidden_field :image
  = f.hidden_field :image_cache
  = f.submit '戻る', name: 'back'

app/views/blogs/edit.html.slim
h2 編集画面

== render 'form'

app/views/blogs/index.html.slim
.card-deck
  .row
    - @blogs.each do |blog| 
      .col-sm-4
        .card
          .card-header #{blog.user.name}
          .card-body
            h5.card-title = link_to "#{blog.title}", blog_path(blog.id)
            p.card-text = blog.content
            - if blog.image.present?
              img.card-img.pb-2 alt="card image" src="#{blog.image.url}" /
            small.text-muted = time_ago_in_words(blog.created_at)

= link_to '新しくブログを投稿する', new_blog_path
/ h1 ブログ一覧

/ table.table.table-hover
/   thead.thead-default
/     tr
/       th タイトル
/       th 内容
/       th 投稿者
/       th 画像
/       th
/       th
/       th
/   tbody
/   - @blogs.each do |blog|
/     tr
/       td = blog.title
/       td = blog.content
/       td = blog.user.name
/       td = image_tag(blog.image.url(:thumb))
/       td = link_to '詳細を確認する', blog_path(blog.id)
/       td = link_to 'ブログを編集する', edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' }
/       td = link_to 'ブログを削除する', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' }

/ = link_to '新しくブログを投稿する', new_blog_path

app/views/blogs/new.html.slim
h2 ブログを作成する

== render 'form'

app/views/blogs/show.html.slim
.card.border-dark.mb-3 style=("max-width: 20rem;") 
  .card-header #{@blog.user.name}
  .card-body
    h4.card-title #{@blog.title}
    p.card-text #{@blog.content}
    img.card-img.pb-2 alt="card image" src="#{@blog.image.url}" /

    / p #{image_tag @blog.image.url}
    - if @blog.user_id == current_user.id
      = link_to 'edit', edit_blog_path(@blog.id), data: { confirm: '本当に編集してよろしいですか？' }, class: 'btn btn-info'
      = link_to 'delete', blog_path(@blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger'
    - else
      - if @favorite.present?
        = link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger'
      - else
        = link_to 'お気に入り登録する', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary'


/ h1 ブログ詳細画面
/ p
/   | タイトル: #{@blog.title}
/ p
/   | 内容: #{@blog.content}
/ p
/   | 投稿者: #{@blog.user.name}
/ p
/   | 画像: #{image_tag @blog.image.url}
/ - unless @blog.user_id == current_user.id
/   - if @favorite.present?
/     = link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger'
/   - else
/     = link_to 'お気に入り登録する', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Fbclone
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div.aoo-title.navbar.navbar-expand-md.navbar-light.bg-light
      div.navbar-brand FBclone
      ul.div.navbar-nav.ml-auto
        - if logged_in?
          li.div.nav-item = link_to "Profile", user_path(current_user.id), class: 'nav-link'
          li.div.nav-item = link_to "Logout", session_path(current_user.id), method: :delete, class: 'nav-link'
        - else
          li.div.nav-item = link_to "Sign Up", new_user_path, class: 'nav-link'
          li.div.nav-item = link_to "Log in", new_session_path, class: 'nav-link'
    div.container-fluid
      - flash.each do |key, value|
        div.alert.alert-success = content_tag(:div, value, class: "#{key}")
      = yield

app/views/users/new.html.slim
h1 Sign Up

- if @user.errors.any?
  #error_explanation
    h2 "#{pluralize(@user.errors.count, "error")} prohibited this #{@user} from being saved:"
    ul
    - @user.errors.full_messages.each do |message|
      li = message

= form_with(model: @user, local:true) do |f|
  div.user_name.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  div.user_email.form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  div.user_password.form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
  div.user_password_confirmation.form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'

  = f.submit "Create my account", class: 'btn btn-primary'

app/views/users/show.html.slim
h1
  | #{current_user.name} のページ
p
  | メールアドレス: #{current_user.email}

= link_to 'ブログ一覧画面', blogs_path